server:
  servlet:
    context-path: /api/v1
    session:
      timeout: ${SESSION_TIMEOUT:20m}

spring:
  config:
    import: application-prod.yml
  profiles:
    active: ${PROFILE_ACTIVE}
  security:
    user:
      name: medinastr
      password: medinastr
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/eazybank_db}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:mysql1530}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      show-sql: true
  jwt:
    secret: ${JWT_SECRET:jetYmfACxddAuexPznq1z5ui9sP6ibIER7vaFO9I4mY=}
    expiration: ${JWT_EXPIRATION:900000} # 15 minutes in milliseconds

logging:
  level:
    org:
      springframework:
        security: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      flywaydb: DEBUG