server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:20m}

spring:
  security:
    user:
      name: medinastr
      password: medinastr
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/eazybank_db}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:mysql1530}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      show-sql: true

logging:
  level:
    org:
      springframework:
        security: ERROR
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      flywaydb: DEBUG